Fs=1000;
t=0:1/Fs:1;
f=3;
f2=15;
f3=150;
x=sin(2*pi*t*f);
x2=sin(2*pi*t*f2);
x3=sin(2*pi*t*f3);
nfft=1024;
X=fft(x,nfft);
X=X(1:nfft/2);
mx=abs(X);
f=(0:nfft/2-1)*Fs/nfft;

X2=fft(y,nfft);
X2=X2(1:nfft/2);
mx2=abs(X2);
f2=(0:nfft/2-1)*Fs/nfft;
z=x+y;
%fft(z);
z2=mx+mx2;
figure(1);
plot(t,z);
title('sine wave signal');
xlabel('Time(s)');
ylabel('Amplitude');
figure(2);
plot(f,z2);
title('power spectrum of a sine wave');
xlabel('frecuency (Hz)');
ylabel('power');
